### ISSUE TITLE
maven build failure

### ISSUE THREAD

**Issue by d-subrahmanyam** [AdeptJ/adeptj-runtime#5]
Rakesh,

When I try to do a mvn clean package, I'm getting a build failure while looking for dependencies 
- com/adeptj/adeptj-modules-commons-webconsole-branding/1.0.0.RELEASE/adeptj-modules-commons-webconsole-branding-1.0.0.RELEASE
- com/adeptj/adeptj-modules-commons-webconsole-security/1.0.0.RELEASE/adeptj-modules-commons-webconsole-security-1.0.0.RELEASE

mvn clean package -U                                                                                                                                                                                  ✓  3138  07:59:48
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AdeptJ Runtime 1.0.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/com/adeptj/adeptj-modules-commons-webconsole-branding/1.0.0.RELEASE/adeptj-modules-commons-webconsole-branding-1.0.0.RELEASE.pom
[WARNING] The POM for com.adeptj:adeptj-modules-commons-webconsole-branding:jar:1.0.0.RELEASE is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/com/adeptj/adeptj-modules-commons-webconsole-security/1.0.0.RELEASE/adeptj-modules-commons-webconsole-security-1.0.0.RELEASE.pom
[WARNING] The POM for com.adeptj:adeptj-modules-commons-webconsole-security:jar:1.0.0.RELEASE is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/com/adeptj/adeptj-modules-commons-webconsole-branding/1.0.0.RELEASE/adeptj-modules-commons-webconsole-branding-1.0.0.RELEASE.jar
Downloading: https://repo.maven.apache.org/maven2/com/adeptj/adeptj-modules-commons-webconsole-security/1.0.0.RELEASE/adeptj-modules-commons-webconsole-security-1.0.0.RELEASE.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.552 s
[INFO] Finished at: 2017-02-28T08:00:30+05:30
[INFO] Final Memory: 13M/301M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project adeptj-runtime: Could not resolve dependencies for project com.adeptj:adeptj-runtime:jar:1.0.6-SNAPSHOT: The following artifacts could not be resolved: com.adeptj:adeptj-modules-commons-webconsole-branding:jar:1.0.0.RELEASE, com.adeptj:adeptj-modules-commons-webconsole-security:jar:1.0.0.RELEASE: Could not find artifact com.adeptj:adeptj-modules-commons-webconsole-branding:jar:1.0.0.RELEASE in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by rakeshk15** [comment]
Hello Subrahmanyam,

Let me work on this, dependencies seem not propagated to central repos.

I'll get back to you ASAP.

Thanks,
Rakesh

**Comment by rakeshk15** [comment]
Hello Subrahmanyam,

This issue is fixed, please pull and build again.

Thanks,
Rakesh
